### ISSUE TITLE
latest release broken

### ISSUE THREAD

**Issue by timrs2998** [gramps-graphql/rest-helpers#1]

**Comment by timrs2998** [comment]
When you `yarn add @gramps/rest-helpers`, you get `1.0.0-beta.1`, which is missing the connector. The `1.0.0-beta.3` is the latest working version, and users have to `yarn add @gramps/rest-helpers@1.0.0-beta.3` to avoid a broken version.

https://www.npmjs.com/package/@gramps/rest-helpers shows `1.0.0-beta.1`

**Comment by timrs2998** [comment]
I figured out the working version number from https://github.com/gramps-graphql/data-source-xkcd/blob/master/package.json#L37

**Comment by jlengstorf** [comment]
@timrs2998 Sorry about that. 1.0.0 should be available now with `yarn add @gramps/rest-helpers@latest`.
